os: linux
dist: focal
language: python
python:
  - "3.9"
cache: pip
branches:
  only:
    - master
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov
install:
  - pip install -r requirements.txt
script:
  - pytest --cov-report xml